### ISSUE TITLE
Question about the use of Launch Configs instead Launch Templates

### ISSUE THREAD

**Issue by pollosp** [terraform-community-modules/tf_aws_asg_elb#11]
Hello, 
This is not really an issue is just curiosity.

Today I was trying to use ASG module with GP3 volumes and the API throw me:
```
Error: Error creating launch configuration: ValidationError: gp3 is invalid. Valid volume types are standard, io1, gp2, st1 and sc1.
	status code: 400, request id: 0ec52c54-3a90-47c3-87a5-3165eaa0c346
```

Looks like LC doesn't support GP3 yet https://forums.aws.amazon.com/thread.jspa?messageID=966379&tstart=0  . 

Reading an looking a little bit deeper I found in https://docs.aws.amazon.com/autoscaling/ec2/userguide/LaunchTemplates.html :

```
We recommend that you create Auto Scaling groups from launch templates to ensure that you're accessing the latest features and improvements. If you plan to continue to use launch configurations with Amazon EC2 Auto Scaling, be aware that not all Auto Scaling group features are available. For example, you cannot create an Auto Scaling group that launches both Spot and On-Demand Instances or that specifies multiple instance types or multiple launch templates. You must use a launch template to configure these features. For more information, see Auto Scaling groups with multiple instance types and purchase options.
In addition to the features of Amazon EC2 Auto Scaling that you can configure by using launch templates, launch templates enable you to use newer features of Amazon EC2. This includes the current generation of EBS volume types (gp3 and io2), EBS volume tagging, T2 Unlimited instances, elastic inference, and Dedicated Hosts, to name a few. Dedicated Hosts are physical servers with EC2 instance capacity that are dedicated to your use. While Amazon EC2 Dedicated Instances also run on dedicated hardware, the advantage of using Dedicated Hosts over Dedicated Instances is that you can bring eligible software licenses from external vendors and use them on EC2 instances. 
```

So is there any reason behind of the use of Launch Configs ? 
Is it worth to change it to  Launch Templates ?

Thanks :)

**Comment by antonbabenko** [comment]
Hi!

Launch Configurations were before AWS released Launch Templates and new features like the one you mentioned about "gp3" volumes are only available when using Launch Templates.

Currently, there is [this PR](https://github.com/terraform-aws-modules/terraform-aws-autoscaling/pull/124) in Terraform AWS modules which is pending review. Once it is merged, you will be able to use "gp3" with autoscaling groups.

Closing this issue here. Hopefully, I answered your question.

BR,
Anton.
