### ISSUE TITLE
userdata from a template file

### ISSUE THREAD

**Issue by lorantfecske** [terraform-community-modules/tf_aws_asg_elb#8]
Hello,

It is more a question than an issue. I have a userdata.sh as a template file with variables. I would like to create ECS cluster instances. My current solution is the following: 

userdata.sh

> #!/bin/bash
> yum install -y aws-cli nfs-utils
> printf '\n%s\n' "ECS_CLUSTER=${aws_ecs_cluster_name}" >> /etc/ecs/ecs.config

cluster.tf

> data "template_file" "userdata" {
> 	template = "${file("userdata.sh")}"
>   vars {
>     aws_ecs_cluster_name = "${var.cluster_name}"
>   }
> ...
> resource "aws_launch_configuration" "ecs_instance" {
>   name_prefix = "${var.cluster_name}-ecs-cluster-instance"
>   instance_type = "t2.small"
>   key_name = "${var.cluster_keypair}"
>   iam_instance_profile = "${aws_iam_instance_profile.ecs_instance.name}"
>   security_groups = ["${aws_security_group.ecs_instance.id}"]
>   image_id = "${var.amazon_ecs_ami_id["${var.region}"]}"
>   user_data = "${data.template_file.userdata.rendered}"

Can I achieve the same with this module and how?

**Comment by antonbabenko** [comment]
Yes, you can do this by replacing `resource "aws_launch_configuration" "ecs_instance" { ... }` with code from the [example](https://github.com/terraform-community-modules/tf_aws_asg_elb/blob/master/example/example.tf#L17). Also make sure that you have `user_data = "${data.template_file.userdata.rendered}"`

**Comment by lorantfecske** [comment]
Thanks 🥇

**Comment by mvparmar1717** [comment]
Hello Everyone,

 trying to call the shell script which i have created and save in the file #user_data = file(setupjava.sh) but that file is not executing could you please help me on this terraform version im using i s0/14
